spring.application.name=GameServer
spring.datasource.url=${DB_URL}
spring.datasource.username=${USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

app.security.pepper=${PEPPER}

spring.jackson.default-property-inclusion=non_null