spring.application.name=GameServer
spring.datasource.url=${DB_URL}?reWriteBatchedInserts=true
spring.datasource.username=${USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

app.security.pepper=${PEPPER}

spring.jackson.default-property-inclusion=non_null

# batching
spring.jpa.properties.hibernate.jdbc.batch_size=100

spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.batch_versioned_data=true

spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=5000

spring.jpa.open-in-view=false